function position = getVertexPosition(id)
ground_truth_file = fopen('MH01/GroundTruthPositions.csv');
textscan(ground_truth_file,'%s', 17, 'Delimiter',',');
groun_truth_all = textscan(ground_truth_file,...
    '%u64 %n %n %n',...
    'Delimiter',',');
fclose(ground_truth_file);

id_to_time = fopen('MH01/vertex_id_to_time.csv');
textscan(id_to_time,'%s', 2, 'Delimiter',',');
vertex_id_to_time_stamp = textscan(id_to_time,...
    '%u64 %s', 'Delimiter',',');
fclose(id_to_time);

index = find(not(cellfun('isempty', ...
            strfind(vertex_id_to_time_stamp{2}, id))));
time_stamp = vertex_id_to_time_stamp{1}(index);

groundtruth_indices = knnsearch(groun_truth_all{1}, ...
                                time_stamp,'k',2);
x2 = [groundtruth_indices{2}(groundtruth_indices(2)),...
      groundtruth_indices{3}(groundtruth_indices(2)),...
      groundtruth_indices{4}(groundtruth_indices(2))];
  
x1 = [groundtruth_indices{2}(groundtruth_indices(1)),...
      groundtruth_indices{3}(groundtruth_indices(1)),...
      groundtruth_indices{4}(groundtruth_indices(1))];
  
position = x2 * double(time_stamp -  groun_truth_all(groundtruth_indices(1), 1)) + ...
    x1 * double(groun_truth_all(groundtruth_indices(2), 1) - time_stamp)/...
    double(groun_truth_all(groundtruth_indices(2), 1) - ...
    groun_truth_all(groundtruth_indices(1), 1))

end